#!/bin/bash
# pageindex-rag 用户使用指南

echo "📚 pageindex-rag 用户指南"
echo "======================================"
echo ""

echo "🚀 快速开始"
echo "--------------------------------------"
echo "1. 基本搜索:"
echo "   cd /root/.openclaw/workspace"
echo "   ./ms.sh \"你的查询\""
echo ""
echo "2. 指定结果数量:"
echo "   ./ms.sh \"查询\" 5"
echo ""
echo "3. 查看完整路径:"
echo "   bash scripts/memory-search-pageindex.sh \"查询\""
echo ""

echo "💡 使用技巧"
echo "--------------------------------------"
echo "✓ 使用关键词而非完整句子"
echo "  例如: \"部署\" 而非 \"如何部署系统\""
echo ""
echo "✓ 尝试不同的关键词"
echo "  例如: \"防护\" \"安全\" \"规则\""
echo ""
echo "✓ 使用文件名匹配"
echo "  如果记得文件名，直接搜索文件名"
echo ""

echo "🎯 最佳实践"
echo "--------------------------------------"
echo "1. 日常使用: 返回 3 条结果"
echo "   ./ms.sh \"查询\" 3"
echo ""
echo "2. 深度搜索: 返回 10 条结果"
echo "   ./ms.sh \"查询\" 10"
echo ""
echo "3. 批量搜索: 使用多个关键词"
echo "   ./ms.sh \"关键词1\" && ./ms.sh \"关键词2\""
echo ""

echo "📊 提供反馈"
echo "--------------------------------------"
echo "如果你有任何反馈，请运行:"
echo "  bash scripts/pageindex-feedback.sh add <查询> <结果数> <满意度> [备注]"
echo ""
echo "示例:"
echo "  bash scripts/pageindex-feedback.sh add \"部署\" 3 5 \"非常准确\""
echo ""

echo "📝 查看统计"
echo "--------------------------------------"
echo "查看反馈统计:"
echo "  bash scripts/pageindex-feedback.sh stats"
echo ""

echo "✅ 开始使用:"
echo "   cd /root/.openclaw/workspace && ./ms.sh \"测试\""
